# Generated by Django 3.1.6 on 2021-02-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='beginner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional',
            field=models.BooleanField(default=False),
        ),
    ]
