# Generated by Django 3.1 on 2021-04-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='bitcoin',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='ethereum',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='ripple',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='tether',
        ),
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(default='hi', max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coin'),
        ),
        migrations.CreateModel(
            name='CoinInWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coin')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wallet')),
            ],
        ),
    ]
