# Generated by Django 3.1.6 on 2021-02-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210225_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bitcoin',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ethereum',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ripple',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tether',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
