# Generated by Django 3.1.6 on 2021-02-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210225_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bitcoin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ethereum',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ripple',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tether',
            field=models.FloatField(default=0, null=True),
        ),
    ]
