# Generated by Django 3.1 on 2021-04-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210412_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='botamount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='botbenefit',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='botdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='botname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='wallet',
            name='botsignal',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
