# Generated by Django 3.1 on 2021-04-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210414_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='botstatus',
            field=models.BooleanField(default=False),
        ),
    ]
