# Generated by Django 3.1.6 on 2021-02-26 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210225_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.FloatField(default=0, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CoinInWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.coin')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wallet')),
            ],
        ),
    ]
