# Generated by Django 3.1.6 on 2021-02-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coin_coininwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coininwallet',
            old_name='album',
            new_name='coin',
        ),
        migrations.RenameField(
            model_name='coininwallet',
            old_name='artist',
            new_name='wallet',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='bitcoin',
        ),
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.CharField(default='hi', max_length=100),
        ),
        migrations.AddField(
            model_name='coininwallet',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
