# Generated by Django 3.1.6 on 2021-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210226_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
