# Generated by Django 3.1.6 on 2021-02-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_wallet_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinInWallet',
            new_name='Transaction',
        ),
    ]
