# Generated by Django 3.1.6 on 2021-04-16 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210415_0007'),
        ('home', '0005_wallet_botstatus'),
    ]

    operations = [
    ]
