# Generated by Django 3.1.6 on 2021-04-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20210415_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='buy',
            new_name='typeOF',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sell',
        ),
    ]
